### ISSUE TITLE
Java client for exceptionless

### ISSUE THREAD

**Issue by pc9795** [exceptionless/Exceptionless.Java#1]
Ref: exceptionless/Exceptionless#123 

👋 After going through the above issue and a quick google search I don't think we have any official client library for Java or I am missing something. I think the repository created for the Java client in the above issue is now deleted. 

My background:
I am currently working on a Java app and need a self-hosting error monitoring solution. I worked with sentry before in a professional setting but want to try exceptionless for my current project.

**Comment by niemyjski** [comment]
Here is the link to the modernized client I've been working on for js: https://github.com/exceptionless/Exceptionless.JavaScript/pull/95

**Comment by pc9795** [comment]
@niemyjski I don't have permission to push code here

**Comment by niemyjski** [comment]
Can you fork and submit a pr and I'll work on getting permissions (on mobile)

**Comment by pc9795** [comment]
😅 I forgot the open-source workflow. An old habit of directly pushing without forking. My active fork: https://github.com/pc9795/Exceptionless.Java

I am porting according to the JS client. After a barebone, I will enhance if there are any issues/requests or I need the features when I use it in my Java app.

**Comment by niemyjski** [comment]
Sounds good, please feel free to submit a pr and we can review / collaborate and get it merged in and then I can make you a maintainer if you'd like.

**Comment by pc9795** [comment]
Sure thing 👍

**Comment by niemyjski** [comment]
Yes, I'll add you, just wanted to let you know we had some docs here on the client sdk (please give us any feedback you may have as we just wrote it): https://exceptionless.com/docs/clients/custom-clients/

**Comment by pc9795** [comment]
I am thinking of just finishing this from my side then you can play with the lib and can raise issues/suggest changes accordingly. PR way will be not much flexible for me as it will induce some friction. Let me know if you think otherwise. 
Sure I will join the Discord to chat/discuss 😄

**Comment by pc9795** [comment]
Closing as basic implementation is ready. Now we can track it using individual issues to be more focused.
