### ISSUE TITLE
Configure artifact publishing to Maven central

### ISSUE THREAD

**Issue by pc9795** [exceptionless/Exceptionless.Java#28]

**Comment by niemyjski** [comment]
Would be good to get github actions setup: https://github.com/exceptionless/Exceptionless.Java/actions/new so we can get builds / tests running with every commit / pr :) I can help if you want I just don't know much about java builds (yet).

**Comment by pc9795** [comment]
Let me have a look 👀. This will be my first open-source project as a maintainer so have to explore. I Will let you know if need help 😄
