### ISSUE TITLE
Add Getting Started section to readme

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless.Java#33]
It would be great to have a [getting started](https://github.com/exceptionless/Exceptionless.Net#getting-started-development) to the readme. This would give some steps of required software to get going and work with the project. We try to have docs for VS Code but that isn't required (I'm also not sure what editor you use or recommend :)).

Also is there a min java version we support?

**Comment by pc9795** [comment]
I used Intellij Ultimate (paid one) to develop this.
Yeah, I will surely update the readme. I was neglecting the fact that everyone has their own dev environment.

**Comment by pc9795** [comment]
I added a getting started section in the readme
