### ISSUE TITLE
Storage Feedback

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless.Java#35]
The Java client was based on the javascript client (real world 
Java client would probably would be closer to the .NET implementation) which has been going a major update / refactoring (https://github.com/exceptionless/exceptionless.javascript/tree/feature/workspaces). 

One of the things we did was simplify storage greatly. We got rid of the storage providers and just have a simple storage implementation that reflects local storage apis (it's what makes sense in java but maybe not necessarily here in terms to the local storage api). This took some reworking of the queue to maintain storage but resulted in some really nice changes with tons of deletions. It didn't make sense to store items by timestamp and caused a lot of extra parsing of storage keys that wasn't needed. Here is the link to the new storage implementation   https://github.com/exceptionless/Exceptionless.JavaScript/tree/feature/workspaces/packages/core/src/storage (here is the .NET one https://github.com/exceptionless/Exceptionless.Net/blob/master/src/Exceptionless/Storage/IObjectStorage.cs) Feel free to do what makes sense I just wanted to let you know why we changed.

We also simplified the Submission as well and got rid of the submission adaptors to a more simplified approach like what you did.

**Comment by pc9795** [comment]
I will check the links you mentioned. Thanks for the feedback

**Comment by pc9795** [comment]
I second you on using a path/key for storing files instead of timestamp generally 🤔. But right now I will leave it as it is and fix it if someone raises an issue.
