### ISSUE TITLE
Plugin/Client Error handlers feedback

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless.Java#40]
## Handling different platforms

In the .NET clients we have we usually have a startup method on ExceptionlessClient that takes a function/predicate with a Configuration object or api key and allows configuration / setting api key and startups timers, applies configuration etc.. We then have multiple packages for different client technologies and we define Register Extension method to hook up any platform error handlers and calls startup.

In the new JavaScript client we just have startup that does the same thing but instead of Register extension methods we export a preconfigured exceptionless client (https://github.com/exceptionless/Exceptionless.JavaScript/blob/feature/workspaces/packages/browser/src/index.ts#L12) for each platform that wires up plugins that register to global error handlers: https://github.com/exceptionless/Exceptionless.JavaScript/blob/28f253ffb2e0b09b113a466860a76a0ddde4d152/packages/browser/src/BrowserExceptionlessClient.ts#L25

This brings me to the question: Do we feel like we'd have many different client technologies we'd support on java that that we'd be wiring up to different error handlers? If so what approach do we want to take? I kinda like the plugin approach but we need an easy way to add them (but it's not to much to ask or provide an easy way later to add default plugins based on the integration).

If we go the plugin route, we added support for [startup and suspend](https://github.com/exceptionless/Exceptionless.JavaScript/blob/feature/workspaces/packages/core/src/plugins/IEventPlugin.ts) to plugins (optional to implement). Here is an [example plugin](https://github.com/exceptionless/Exceptionless.JavaScript/blob/feature/workspaces/packages/browser/src/plugins/BrowserGlobalHandlerPlugin.ts) (We just gotta make sure we only wire up one handler if startup is called multiple times).

## Event Plugin Context:
Since plugins are really dynamic, it might be nice to just store exception, unhandled error submission method and request in a data bag (dictionary<string,object>). This way users can add there own things to it. We don't have to do this but it seems like it would be nice.

### Error plugin 
For the error plugin the exclusions was extra properties that are stored on the Exception object that we didn't want to include in an errors extended data that we capture. We'd want to update this for java or remove it.

### Module info
We should cache this as I'm guessing this is expensive to compute every time run is called.

## Duplicate Checker: 
The merged event hash isn't used (at least that's what vs code is telling me.

This plugin should be checking all event types and not just errors, but this is a good starting place!

**Comment by pc9795** [comment]
@niemyjski I too like the plugin approach of providing extensions. I don't have any ideas on any specific functionalities to support other Java libraries. I guess we should wait for requests/issues for that.
Right now we can add custom plugins like this.
```
    ConfigurationManager configurationManager =
        ConfigurationManager.builder()
            .configuration(
                Configuration.builder().serverUrl("server-url").apiKey("api-key").build())
            .build();
    configurationManager.addPlugin(
        "plugin-name", 100, (ctx, cm) -> System.out.println("Do something"));
    ExceptionlessClient client =
        ExceptionlessClient.builder().configurationManager(configurationManager).build();
```

**Comment by pc9795** [comment]
I didn't understand the concept of `startup` and `suspend` methods 💭

**Comment by pc9795** [comment]
> Event Plugin Context:
> Since plugins are really dynamic, it might be nice to just store exception, unhandled error submission method and request in a data bag (dictionary<string,object>). This way users can add there own things to it. We don't have to do this but it seems like it would be nice.

We have this: https://github.com/exceptionless/Exceptionless.Java/blob/main/src/main/java/com/exceptionless/exceptionlessclient/models/EventPluginContext.java

**Comment by pc9795** [comment]
> The merged event hash isn't used (at least that's what vs code is telling me.

I am pretty sure Intellij would've caught if something is not used 😛 . I also have unit tests 🤔

**Comment by pc9795** [comment]
> Error plugin
> For the error plugin the exclusions was extra properties that are stored on the Exception object that we didn't want to include in an errors extended data that we capture. We'd want to update this for java or remove it.

https://github.com/exceptionless/Exceptionless.Java/pull/48

**Comment by pc9795** [comment]
> Module info
> We should cache this as I'm guessing this is expensive to compute every time run is called.

https://github.com/exceptionless/Exceptionless.Java/pull/49

**Comment by pc9795** [comment]
> Duplicate Checker:
> The merged event hash isn't used (at least that's what vs code is telling me.
> 
> This plugin should be checking all event types and not just errors, but this is a good starting place!

https://github.com/exceptionless/Exceptionless.Java/pull/50

**Comment by niemyjski** [comment]
> > If we go the plugin route, we added support for startup and suspend to plugins (optional to implement). Here is an example plugin (We just gotta make sure we only wire up one handler if startup is called multiple times).
> 
> I didn't understand the concept of `startup` and `suspend` methods 💭

I added them to javascript client and we will probably add them to .NET as well. It's purpose is to call those plugin methods when the client is starting up and shutting down so you can unwire or do extra logic during those lifecycle events. It makes it much cleaner to wireup and do things to the client via a plugin then relying on event handlers/hacks

**Comment by pc9795** [comment]
For start-up and suspend methods I think we can create separate issues when needed. I will close this one. And also feel free to tag me in the PR for the C# client so I can get some hints.
