### ISSUE TITLE
How can i and Exceptionless support to my java-web application

### ISSUE THREAD

**Issue by kuzank** [exceptionless/Exceptionless.Java#63]
I have a java-web application(springboot) and it build with maven,now i want to and Exceptionless support but i can't find it on Maven Central.

I had download Exceptionless.Java code and run "mvn build" command but get false.

my jdk version is 1.8.0_241

so what can i do to this

**Comment by pc9795** [comment]
Hey there, we are still in the process of making this lib available on maven. Hopefully, it will be available by the end of last week. 
For time being you can test the lib by using `mvn clean install` after cloning the repo and then you can run locally.
I can see you are using Java 8 but the lib is built using Java 11.

**Comment by pc9795** [comment]
This library is now available at maven central:  https://mvnrepository.com/artifact/com.exceptionless/exceptionless-client
