### ISSUE TITLE
about excptionless-spring-boot-starter

### ISSUE THREAD

**Issue by ghost** [exceptionless/Exceptionless.Java#67]
where can i find the excptionless-spring-boot-starter?
I'm really need this component @niemyjski @pc9795

**Comment by niemyjski** [comment]
I'm not sure what you are asking for. Can you please elaborate?

**Comment by pc9795** [comment]
Hi @zen-arch correct me if I am wrong, but can't you declare exception-less client as a bean in one of your configuration classes like here: https://github.com/exceptionless/Exceptionless.Java/blob/4b3e2232ddf2d46e589dc21ee05e989f718b6549/samples/example-spring-boot-app/src/main/java/com/exceptionless/example/spring/boot/app/ExampleAPI.java#L15

And then use it anywhere like this: 
https://github.com/exceptionless/Exceptionless.Java/blob/4b3e2232ddf2d46e589dc21ee05e989f718b6549/samples/example-spring-boot-app/src/main/java/com/exceptionless/example/spring/boot/app/api/ExampleResource.java#L24

There is an examples spring boot app in the repo - https://github.com/exceptionless/Exceptionless.Java/tree/main/samples/example-spring-boot-app

Let me know if it works for you. Thanks
