### ISSUE TITLE
error datetime in exceptionless-client 0.1.0

### ISSUE THREAD

**Issue by ghost** [exceptionless/Exceptionless.Java#68]
error datetime in exceptionless-client 0.1.0 @niemyjski @pc9795 
![image](https://user-images.githubusercontent.com/37175924/149300492-0a2f2c6d-36f6-4420-819b-d7fff10a5657.png)
![image](https://user-images.githubusercontent.com/37175924/149300557-a58490f7-ce2c-4209-a8a8-46f9c0c76fde.png)

**Comment by niemyjski** [comment]
This should be a OffsetDateTime, would you mind submitting a pr for this.

**Comment by pc9795** [comment]
Nice find. It should have a date component 👍
